### ISSUE TITLE
How to change the shortcut key? Ctrl + S/V

### ISSUE THREAD

**Issue by zhushizhou** [jogeen/StopCoding#2]
How to change the shortcut key? Ctrl + S/V is more important when writing code.

**Comment by jogeen** [comment]
You can modify it as follows





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jogeen/StopCoding"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月13日(星期三) 晚上7:04
收件人:&nbsp;"jogeen/StopCoding"<StopCoding@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jogeen/StopCoding] How to change the shortcut key? Ctrl + S/V (#2)





 
How to change the shortcut key? Ctrl + S/V is more important when writing code.

**Comment by jogeen** [comment]
> How to change the shortcut key? Ctrl + S/V is more important when writing code.

Setting->keymap->StopCoding ->remove
